- name: Git Repositorys Create a ext4 filesystem on /dev/sdb and check disk blocks
  filesystem:
    fstype: ext4
    dev: "{{ disk1 }}"

- name: Create mount point
  file:
    path: /harbor
    owner: root
    group: root
    mode: '2775'
    state: directory
    
- name: Mount up device by {{ disk1 }}
  mount:
    path: "{{ disk_sdc }}"
    src:  "{{ disk1 }}"
    fstype: ext4
    state: mounted
